### PR TITLE
added feature, formatted, implemented #3 solve #12 and #14

### PR DESCRIPTION
**Pull request by JoostScheffer**
- Format code
- add solution for Issue #3 using deque
- add typehints
- implement button to recenter
- implement button to clear plot
- added random noise to testdata to beter visualise #3

### CODE REVIEW

**Comment by JoostScheffer** [comment]
reformatted code
split functions into multiple more general functions
more consistent usage of `data`
removed `self.data`

added:
- typehints
- coloured plot and table-row for calibration measurement
- horizontal and vertical labels for table
- automatic restore axis button
- clear graph and clear calibration buttons
- label to tell user if dummy data is being used

**Comment by jurc192** [comment]
Hey @JoostScheffer
thanks for your time and software contribution to this project! Your pull request is on-point and exactly what we were hoping for :)

I have some questions and comments before merging it:
1. **When I checkout your branch, it does not run out-of-the-box. Steps I took**:
    ```
    $ git pull
    $ pipenv install
    $ pipenv shell
    (pipenv shell) $ ./psplot.py
    ```
    last command outputs the following:
    ```
    App is running on QT version 6.3.1
    Opened serial port /dev/ttyACM0
    Traceback (most recent call last):
      File "./psplot.py", line 418, in <module>
        window = PsPlot()
      File "./psplot.py", line 206, in __init__
        self.pw.setFocus(True)
    TypeError: arguments did not match any overloaded call:
      setFocus(self): too many arguments
      setFocus(self, Qt.FocusReason): argument 1 has unexpected type 'bool'
    ```
    I am guessing it's something to do with PyQt version differences (need to look into this). Used python version is 3.8.13, PyQt version is 6.3.1.
    Commenting out the line 206 (`self.pw.setFocus(True)`) makes it work though!

2. **Nicer handling of data, getting rid of `self.data`**
    I like how you cleaned up the data handling, splitting up of data obtaining, storage and plotting.
    However, `dataCalibrated` on ine 293 is never used - what was the intention there?

3. **Python stuff**
    Just for (my) educational purposes and curiosity:
    - what's the thing with type hints? Is it common to use them? Why?
    - I noticed you changed " to ' at some places and vice versa. Is there a convention in Python when to use which?

4. **PyQt versions**
    I am not sure how pyqtplot and pyqt dependecies interact with eachother - something to look into. How did you figure out that pyqtplot uses pyqt5? Can you convince me a bit more that using pyqt's internal qt is conventional and a good idea? :)
    Let's try to figure out the best set of dependencies and improve Pipfile so that dependecies become non-ambiguous and working for everyone, hopefully.

Also thanks for implementing sticky readings and fixing the bugs!

**Comment by JoostScheffer** [comment]
Thanks for the feedback and questions.

1. I made a mistake, `setFocus` doesn't require any arguments.
2. I is unclear to me what it is supposed to do. 
I get that the data is divided by the calibration but it seemed off since the default scaling is set in a way which plots the calibrated data out of view.
If this was on purpose, then I would suggest something like a notification for when the user measures without prior calibration.
Currently when a measurement takes place the values of `data` will hover around `0.2`. But after calibration it will be plotted in the vicinity of `1`. When using the axis scaling that was hardcoded only values below `yMax` (`yMax` is set to 0.35 V) will be visible (without panning).
Also the unit on the vertical axis is Volts, but when calibration takes place the measurement would be unit-less because we divide a voltage by another voltage. 
Because these things seemed off to me I disabled it for now.
I wouldn't mind implementing it in the desired way, but I currently just don't know what the desired behaviour is. 

3. Depends, I believe some linters, documentation generators and IDE's use it. When it comes to function arguments I would recommend the use of typehints when the datatype is not explicit. When it comes to returntype I added it to be consistent. 
Instead of typehints the types could be documented in docstrings. Since there weren't any docstrings and the usage of functions wasn't very clear to me I just used them. I can remove them if you like.
For formatting I usually use [Black](https://pypi.org/project/black/) it is a very aggressive formatter which changes the `'` to `"`. One of the side-effects to using Black also is that it often likes to expand lists to take up multiple lines, like it has done with `wavelengths`. I personally don't always like it but I like consistent formatting. And Black is just very aggressive when it comes to formatters. 
4. From what I understand `pyqtplot` inherits it's classes from `pyqt5`. 

For example when `pg.PlotWidget` is called it creates an instance of the `PlotWidget` class. (from the sourcecode of `pyqtplot`): 
```python
class PlotWidget(GraphicsView):
``` 
`GraphicsView` is defined as 
```python 
class GraphicsView(QtWidgets.QGraphicsView):
```
and the import statement for QtWidgets is 
```python
from ..Qt import QT_LIB, QtCore, QtGui, QtWidgets
```
which references the QT library within `pyqtgraph`.
To check which version of QT `pyqtgraph` uses I used
```python
from pyqtgraph.Qt.QtCore import QT_VERSION_STR
print(QT_VERSION_STR)
``` 
which told me it uses QT version `5.15.3` (which is also the current QT version for `PyQt5`.

A problem arises when QT6 is used, namely uppon calling `pg.Plotwidget` there is no `QApplication` with a `QGraphicsView` (or at least not a "compatible" one). I'm not sure why they aren't compatible. 
Using QT 6 and calling `pg.Plotwidget` raises Exceptions, causing the following ouput:
```
QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped)
```
I personally find this weird since on [https://github.com/pyqtgraph/pyqtgraph](https://github.com/pyqtgraph/pyqtgraph) it is stated that QT version 6.3 is supported (which is the version I tried it with).
Perhaps there is a way to have `pyqtgraph` use version 6 instead of version 5 but I could not find one.

Since QT 6 apparently can't be used there are 2 ways of importing QT.
import QT with 
```python
from PyQt5.<> import <>
``` 
which requires a separate installation of `pyqt5` or use the QT that already comes with `pyqtgraph` (and is probably guaranteed to be compatible with `pyqtgraph`)
```python
from pyqtgraph.Qt.<> import <>
```

I would suggest using the later one until compatibility with QT6 has been figured out.

Please say so if you still have questions

**Comment by JoostScheffer** [comment]
tomorrow I will (probably) commit a local branch to this pullrequest. I should contain a fix for issue 1 you mentioned and implement #16

**Comment by JoostScheffer** [comment]
#16 is now partially implemented

**Comment by jurc192** [comment]
Ok, this looks good to me. Now it's much more clear about the pyqt and qt versions, thanks for pointing out the relevant docs!
Next time, let's try to make commits and pull request more fine-grained; now we did a lot of different stuff in one PR (e.g. the color theming is another topic which imo deserves a separate commit/issue/pr).

BTW: you are the first (code) contributor to the Plastic Scanner, hoorray! :smile:

**Comment by JoostScheffer** [comment]
will do

**Pull request merged**
